### ISSUE TITLE
report builder download

### ISSUE THREAD

**Issue by closurefyre** [dustingtorres/surefyre-tickets#48] opened 2017-09-12 22:01 UTC
![screen shot 2017-09-12 at 2 59 43 pm](https://user-images.githubusercontent.com/29260883/30350309-07ce7d6a-97cb-11e7-81a7-86cf29f5ee31.png)

takes a long time to download and when I opened document, wrong info

**Comment by dustingtorres** [comment] 2017-09-13 05:47
Closing since we cannot reproduce

**Closed as completed by dustingtorres** 2017-09-13 05:47 UTC
Labels: bug
