### ISSUE TITLE
Adding a product that already exists renders tags field incorrectly

### ISSUE THREAD

**Issue by dustingtorres** [dustingtorres/surefyre-tickets#10] opened 2017-06-09 01:46 UTC
Browser: Chrome

Steps to reproduce:
1.) Navigate to a lead that already has a product
2.) Add a new product of the same type.

Expected results: New product rendered correctly

Actual results: Tags field is incorrectly rendered

**Comment by closurefyre** [comment] 2017-06-27 20:23
duplicate of #9

**Closed as completed by closurefyre** 2017-06-27 20:23 UTC
